export enum ERRAND_CATEGORIES {
  DELIVERY = 'DELIVERY',
  SHOPPING = 'SHOPPING',
  CLEANING = 'CLEANING',
  REPAIR = 'REPAIR',
  PROXY = 'PROXY',
  PET = 'PET',
  CAR_WASH = 'CAR_WASH',
  ETC = 'ETC',
}
